<?php

return [
    'apps' => [
        'asset' => [
            'name' => 'Asset Management',
            'url' => env('APP_ASSET_URL', 'http://127.0.0.1:8000/api/v1/auth/sso/direct-login?redirect=/'),
            'roles' => ['staff', 'kepala_seksi', 'kepala seksi', 'verifikator', 'admin', 'auditor', 'diskominfo'],
            'default_route' => '/Dashboard',
            'role_routes' => [
                'kepala_seksi' => '/verifikator',
                'kepala seksi' => '/verifikator',
                'verifikator' => '/verifikator',
                'staff' => '/Dashboard',
            ],
            'role_urls' => [
                'staff' => env('APP_ASSET_URL_STAFF', 'https://dinas-siprima.vercel.app/'),
                'user_dinas' => env('APP_ASSET_URL_STAFF', 'https://dinas-siprima.vercel.app/'),
                'dinas' => env('APP_ASSET_URL_STAFF', 'https://dinas-siprima.vercel.app/'),
                'admin' => env('APP_ASSET_URL_STAFF', 'https://dinas-siprima.vercel.app/'),
                'auditor' => env('APP_ASSET_URL_AUDITOR', 'https://auditor-siprima.vercel.app/'),
                'diskominfo' => env('APP_ASSET_URL_DISKOMINFO', 'https://diskominfo-siprima.vercel.app/'),
                'kepala_seksi' => env('APP_ASSET_URL_KEPALA_SEKSI', 'https://verifikator-siprima.vercel.app/'),
                'kepala seksi' => env('APP_ASSET_URL_KEPALA_SEKSI', 'https://verifikator-siprima.vercel.app/'),
                'verifikator' => env('APP_ASSET_URL_KEPALA_SEKSI', 'https://verifikator-siprima.vercel.app/'),
            ],
            'description' => 'Aset Management System',
            'icon' => 'siprima.png',
        ],
        'maintenance' => [
            'name' => 'Service Desk',
            'url' => env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000'),
            'roles' => ['*'],
            'default_route' => '/',
            'role_urls' => [
                'staff' => env('APP_SERVICE_DESK_URL_STAFF', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'admin' => env('APP_SERVICE_DESK_URL_ADMIN', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'kepala_seksi' => env('APP_SERVICE_DESK_URL_KEPALA_SEKSI', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'kepala seksi' => env('APP_SERVICE_DESK_URL_KEPALA_SEKSI', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'kepala_bidang' => env('APP_SERVICE_DESK_URL_KEPALA_BIDANG', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'teknisi' => env('APP_SERVICE_DESK_URL_TEKNISI', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
                'diskominfo' => env('APP_SERVICE_DESK_URL_DISKOMINFO', env('APP_SERVICE_DESK_URL', 'http://127.0.0.1:8000')),
            ],
            'description' => 'Service Desk Management',
            'icon' => 'sindra.png',
        ],
        'change' => [
            'name' => 'Change Management',
            'url' => env('APP_CHANGE_URL', 'http://127.0.0.1:8000'),
            'roles' => ['*'],
            'default_route' => '/',
            'role_urls' => [
                'staff' => env('APP_CHANGE_URL_STAFF', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'admin' => env('APP_CHANGE_URL_ADMIN', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'kepala_seksi' => env('APP_CHANGE_URL_KEPALA_SEKSI', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'kepala_bidang' => env('APP_CHANGE_URL_KEPALA_BIDANG', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'kepala_dinas' => env('APP_CHANGE_URL_KEPALA_DINAS', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'diskominfo' => env('APP_CHANGE_URL_DISKOMINFO', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
                'auditor' => env('APP_CHANGE_URL_AUDITOR', env('APP_CHANGE_URL', 'http://127.0.0.1:8000')),
            ],
            'description' => 'Change & Configuration Management',
            'icon' => 'simantic.png',
        ],
    ],
    'dashboards' => [
        'asset' => [
            'staff' => 'dashboard.staff',
            'kepala_seksi' => 'dashboard.kasi',
            'auditor' => 'dashboard.auditor',
            'diskominfo' => 'dashboard.diskominfo',
            'admin' => null,
            'kepala_bidang' => null,
            'kepala_dinas' => null,
            'teknisi' => null,
        ],
        'change' => [
            'staff' => 'dashboard.staff',
            'admin' => 'dashboard.admin',
            'kepala_seksi' => 'dashboard.kasi',
            'kepala_bidang' => 'dashboard.kabid',
            'kepala_dinas' => 'dashboard.kadis',
            'auditor' => 'dashboard.audit',
            'diskominfo' => 'dashboard.diskominfo',
            'teknisi' => null,
        ],
        'service' => [
            'staff' => 'dashboard.staff',
            'admin' => 'dashboard.admin',
            'kepala_seksi' => 'dashboard.kasi',
            'kepala_bidang' => 'dashboard.kabid',
            'teknisi' => 'dashboard.teknisi',
            'diskominfo' => 'dashboard.diskominfo',
            'kepala_dinas' => null,
            'auditor' => null,
        ],
    ],
];
